### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by lihongzhao99** [donghao51/MOOSA#1]
Hello! Your paper is very inspiring to me. However, I have encountered some confusion during the process of learning your code.

1. It seems that feature separation and supervised contrastive learning of SimMMDG are used in the code, but this is not described in the article. This makes me very confused about whether feature separation is performed in your code.
2. In the code, I found that it seems that the classification loss of each modality is calculated, such as output_loss1, 2, and 3 in the code. I would like to know what is the role of doing this? Which part in the article does the description correspond to?
3. I read the code about “Multimodal Jigsaw Puzzles“ and found that it operates on the "parts" feature, and "parts" is obtained by adding multiple modal features. Would it be more reasonable to use "feat"? "feat" is obtained by concatenating multiple modal features. (This feature seems to correspond more to the description in the paper).

Thanks!

**Comment by donghao51** [comment]
Hello, thanks for your question!

1. We describe it in **B Implementation Details**. We adopt SimMMDG as the base framework due to its demonstrated efficacy in multimodal DG tasks.
![image](https://github.com/user-attachments/assets/2a9f62ed-56f7-4169-b1a7-e903c8318392)

2. It is for Entropy Weighting and used in formula (5)
![image](https://github.com/user-attachments/assets/ba27c168-3501-4b98-8e9d-c1492e63af0f)

3. We use the concat rather than add, please check the code carefully
